//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::alerts::Entity as Alerts;
pub use super::alerts_annotations::Entity as AlertsAnnotations;
pub use super::alerts_labels::Entity as AlertsLabels;
pub use super::annotations::Entity as Annotations;
pub use super::common_annotations::Entity as CommonAnnotations;
pub use super::common_labels::Entity as CommonLabels;
pub use super::groups::Entity as Groups;
pub use super::groups_common_annotations::Entity as GroupsCommonAnnotations;
pub use super::groups_common_labels::Entity as GroupsCommonLabels;
pub use super::groups_labels::Entity as GroupsLabels;
pub use super::labels::Entity as Labels;
