//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "alert_status")]
pub enum AlertStatus {
    #[sea_orm(string_value = "firing")]
    Firing,
    #[sea_orm(string_value = "resolved")]
    Resolved,
}
