[workspace]

resolver = "2"

members = [
    "models",
    "push/push_definitions",
    "push/push_server",
    "plugins/plugins_definitions",
]

[workspace.dependencies]
tracing = { version = "0.1.37" }
async-trait = "0.1.74"
thiserror = "1.0.50"
anyhow = "1.0.75"
schemars = "0.8.15"
serde = { version = "1.0.192", features = ["derive"] }
axum = "0.6.20"
aide = { version = "0.12.0", features = ["axum"] }
tokio = { version = "1.34.0", features = ["full"] }
