[workspace]

members = ["alertmanager_api_v2", "push/push_definitions"]

[workspace.dependencies]
tracing = { version = "0.1.37" }
async-trait = "0.1.74"
thiserror = "1.0.50"
schemars = "0.8.15"
serde = { version = "1.0.192", features = ["derive"] }
