server:
  host: localhost
  port: 5050
plugins:
  file_plugin:
    - meta:
        name: json_file_plugin
        group: default
      config:
        dir_path: dev/data/json_pushes
        file_type:
          type: Json
    - meta:
        name: jinja_file_plugin
        group: default
      config:
        dir_path: dev/data/jinja_pushes
        file_type:
          type: Jinja
          template: models_utilities/jinja_renderer/example-template.j2
  filter_plugin:
    - meta:
        name: filter_plugin_1
        group: default
      config:
        webhook_url: http://localhost:5050/push
        group_labels:
          - type: Drop
            regex: ^.*$
            target: Name
          - type: Add
            name: Label1
            value: Value1
        common_labels:
          - type: Drop
            regex: ^.*$
            target: Name
        common_annotations:
          - type: Replace
            regex: ^.*$
            target: Value
            replace_with: replaced Value!
            replacement_target: Value
        alerts_labels:
          - type: Drop
            regex: ^.*$
            target: Name
        alerts_annotations: []

  postgres_plugin:
    - meta:
        name: postgres_plugin_1
        group: default
      config:
        connection_string: postgres://user:password@localhost:5432/database
        max_connections: 15
        connection_timeout:
          secs: 10
          nanos: 0
  postgres_sea_plugin:
    - meta:
        name: postgres_sea_plugin_1
        group: default
      config:
        connection_string: postgres://user:password@localhost:5434/database
        max_connections: 15
        connection_timeout:
          secs: 10
          nanos: 0
  postgres_x_plugin:
    - meta:
        name: postgres_x_plugin_1
        group: default
      config:
        connection_string: postgres://user:password@localhost:5433/database
        max_connections: 15
        connection_timeout:
          secs: 10
          nanos: 0
  print_plugin:
    - meta:
        name: debug_print_plugin
        group: default
      config:
        print_type:
          type: Debug
    - meta:
        name: jinja_print_plugin
        group: default
      config:
        print_type:
          type: Jinja
          template: models_utilities/jinja_renderer/example-template.j2
  sqlite_plugin:
    - meta:
        name: sqlite_plugin_1
        group: default
      config:
        connection_string: file:dev/data/db/sqlite.db
