/*
 * Alertmanager API
 *
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlertmanagerConfig {
    #[serde(rename = "original")]
    pub original: String,
}

impl AlertmanagerConfig {
    pub fn new(original: String) -> AlertmanagerConfig {
        AlertmanagerConfig {
            original,
        }
    }
}


