/*
 * Alertmanager API
 *
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Matcher {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "isRegex")]
    pub is_regex: bool,
    #[serde(rename = "isEqual", skip_serializing_if = "Option::is_none")]
    pub is_equal: Option<bool>,
}

impl Matcher {
    pub fn new(name: String, value: String, is_regex: bool) -> Matcher {
        Matcher {
            name,
            value,
            is_regex,
            is_equal: None,
        }
    }
}


