/*
 * Alertmanager API
 *
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostableSilence {
    #[serde(rename = "matchers")]
    pub matchers: Vec<crate::models::Matcher>,
    #[serde(rename = "startsAt")]
    pub starts_at: String,
    #[serde(rename = "endsAt")]
    pub ends_at: String,
    #[serde(rename = "createdBy")]
    pub created_by: String,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl PostableSilence {
    pub fn new(matchers: Vec<crate::models::Matcher>, starts_at: String, ends_at: String, created_by: String, comment: String) -> PostableSilence {
        PostableSilence {
            matchers,
            starts_at,
            ends_at,
            created_by,
            comment,
            id: None,
        }
    }
}


