/*
 * Alertmanager API
 *
 * API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionInfo {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "revision")]
    pub revision: String,
    #[serde(rename = "branch")]
    pub branch: String,
    #[serde(rename = "buildUser")]
    pub build_user: String,
    #[serde(rename = "buildDate")]
    pub build_date: String,
    #[serde(rename = "goVersion")]
    pub go_version: String,
}

impl VersionInfo {
    pub fn new(version: String, revision: String, branch: String, build_user: String, build_date: String, go_version: String) -> VersionInfo {
        VersionInfo {
            version,
            revision,
            branch,
            build_user,
            build_date,
            go_version,
        }
    }
}


