//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod alerts;
pub mod alerts_annotations;
pub mod alerts_labels;
pub mod annotations;
pub mod common_annotations;
pub mod common_labels;
pub mod groups;
pub mod groups_common_annotations;
pub mod groups_common_labels;
pub mod groups_labels;
pub mod labels;
pub mod sea_orm_active_enums;
